import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import CardUser from "@/components/CardUser";
import Navbar from "@/components/Navbar";

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreFranklin.className} p-25 antialiased bg-[#1D1C1D] grid grid-cols-[3fr_6fr_0.2fr] gap-4     `}
      >
        <div>
          <CardUser />
        </div>
        <div>{children}</div>
        <div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
